baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "GetInspired365 - Home"

[taxonomies]
  tag = "tags"
  writer = "writers"
  
[params]
 tagsLimit_TopBar = 11
 tagsLimit_HomePage = 12

