baseURL = "https://blissful-babbage-166826.netlify.com/"
languageCode = "en-us"
title = "GetInspired365 - Home"

[taxonomies]
  tag = "tags"
  writer = "writers"
  
[params]
 tagsLimit_TopBar = 11
 tagsLimit_HomePage = 12

