baseURL = "https://happy-villani-795c50.netlify.com/"
languageCode = "en-us"
title = "GETINSPIRED365 | Inspiration"

[taxonomies]
  author = "authors"
  tag = "tags"
  video = "videos"
  
 [params]
 tagsLimit_TopBar = 5
 tagsLimit_HomePage = 8